# https://taskfile.dev

version: '3'

tasks:
  default:
    - task: build

  review:
    desc: Analyzes source code with elm-review
    cmds:
      - elm-review
    sources:
      - src/**/*.elm

  build:
    desc: Compiles all Elm files to our assets/elm.js
    cmds:
      - elm make --output=assets/elm.js --optimize src/Main.elm
    sources:
      - src/**/*.elm
    generates:
      - assets/elm.js
