-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module IdScalarCodecs exposing (Id, codecs)

import Api.Scalar
import Json.Decode as Decode
import Json.Encode as Encode


type alias Id =
    Int


codecs : Api.Scalar.Codecs Id
codecs =
    Api.Scalar.defineCodecs
        { codecId =
            { encoder = \v -> Encode.int v
            , decoder = Decode.int
            }
        }
