# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: Runs the tasks format, test and build
    cmds:
      - task: format
      - task: test
      - task: build

  get-roc:
    desc: Downloads the latest nightly build of roc and unzips it
    cmds:
      - wget https://github.com/roc-lang/roc/releases/download/nightly/roc_nightly-linux_x86_64-latest.tar.gz --output-document roc.tar.gz
      - tar -xf roc.tar.gz
      - rm roc.tar.gz

  format:
    desc: Formats roc files
    cmds:
      - roc format main.roc Server/*.roc
    sources:
      - main.roc
      - Server/*.roc

  test:
    desc: Runs checks and tests
    cmds:
      - roc format --check main.roc Server/*.roc
      - roc check
      - roc test
    sources:
      - main.roc
      - Server/*.roc

  build:
    desc: Builds project without running it
    deps:
      - test
    cmds:
      - rm -f webserver
      - rm -f platform/roc.o
      - roc build --no-link --output platform/roc.o
      - task: build-platform
      - rm platform/roc.o
    sources:
      - main.roc
      - Server/*.roc
      - Server/templates/*.html
    generates:
      - webserver

  build-platform:
    internal: true
    desc: Builds only the webserver
    dir: ./platform
    cmds:
      - go build -o ../webserver

  run-server:
    desc: Runs the webserver
    deps:
      - build
    cmds:
      - ./webserver
