-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Mutation exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import IdScalarCodecs
import Json.Decode as Decode exposing (Decoder)


type alias AddCampaignOptionalArguments =
    { days : OptionalArgument (List String) }


type alias AddCampaignRequiredArguments =
    { title : String }


addCampaign :
    (AddCampaignOptionalArguments -> AddCampaignOptionalArguments)
    -> AddCampaignRequiredArguments
    -> SelectionSet decodesTo Api.Object.Campaign
    -> SelectionSet decodesTo RootMutation
addCampaign fillInOptionals____ requiredArgs____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { days = Absent }

        optionalArgs____ =
            [ Argument.optional "days" filledInOptionals____.days (Encode.string |> Encode.list) ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "addCampaign" (optionalArgs____ ++ [ Argument.required "title" requiredArgs____.title Encode.string ]) object____ Basics.identity


type alias UpdateCampaignRequiredArguments =
    { id : IdScalarCodecs.Id
    , title : String
    }


updateCampaign :
    UpdateCampaignRequiredArguments
    -> SelectionSet decodesTo Api.Object.Campaign
    -> SelectionSet decodesTo RootMutation
updateCampaign requiredArgs____ object____ =
    Object.selectionForCompositeField "updateCampaign" [ Argument.required "id" requiredArgs____.id (IdScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId), Argument.required "title" requiredArgs____.title Encode.string ] object____ Basics.identity


type alias DeleteCampaignRequiredArguments =
    { id : IdScalarCodecs.Id }


deleteCampaign :
    DeleteCampaignRequiredArguments
    -> SelectionSet Bool RootMutation
deleteCampaign requiredArgs____ =
    Object.selectionForField "Bool" "deleteCampaign" [ Argument.required "id" requiredArgs____.id (IdScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId) ] Decode.bool


type alias AddDayRequiredArguments =
    { campaignID : IdScalarCodecs.Id
    , title : String
    }


addDay :
    AddDayRequiredArguments
    -> SelectionSet decodesTo Api.Object.Day
    -> SelectionSet decodesTo RootMutation
addDay requiredArgs____ object____ =
    Object.selectionForCompositeField "addDay" [ Argument.required "campaignID" requiredArgs____.campaignID (IdScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId), Argument.required "title" requiredArgs____.title Encode.string ] object____ Basics.identity


type alias UpdateDayRequiredArguments =
    { id : IdScalarCodecs.Id
    , title : String
    }


updateDay :
    UpdateDayRequiredArguments
    -> SelectionSet decodesTo Api.Object.Day
    -> SelectionSet decodesTo RootMutation
updateDay requiredArgs____ object____ =
    Object.selectionForCompositeField "updateDay" [ Argument.required "id" requiredArgs____.id (IdScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId), Argument.required "title" requiredArgs____.title Encode.string ] object____ Basics.identity


type alias DeleteDayRequiredArguments =
    { id : IdScalarCodecs.Id }


deleteDay :
    DeleteDayRequiredArguments
    -> SelectionSet Bool RootMutation
deleteDay requiredArgs____ =
    Object.selectionForField "Bool" "deleteDay" [ Argument.required "id" requiredArgs____.id (IdScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId) ] Decode.bool


type alias AddEventOptionalArguments =
    { dayIDs : OptionalArgument (List IdScalarCodecs.Id) }


type alias AddEventRequiredArguments =
    { campaignID : IdScalarCodecs.Id
    , title : String
    , capacity : Int
    , maxSpecialPupils : Int
    }


addEvent :
    (AddEventOptionalArguments -> AddEventOptionalArguments)
    -> AddEventRequiredArguments
    -> SelectionSet decodesTo Api.Object.Event
    -> SelectionSet decodesTo RootMutation
addEvent fillInOptionals____ requiredArgs____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { dayIDs = Absent }

        optionalArgs____ =
            [ Argument.optional "dayIDs" filledInOptionals____.dayIDs ((IdScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId) |> Encode.list) ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "addEvent" (optionalArgs____ ++ [ Argument.required "campaignID" requiredArgs____.campaignID (IdScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId), Argument.required "title" requiredArgs____.title Encode.string, Argument.required "capacity" requiredArgs____.capacity Encode.int, Argument.required "maxSpecialPupils" requiredArgs____.maxSpecialPupils Encode.int ]) object____ Basics.identity


type alias UpdateEventOptionalArguments =
    { title : OptionalArgument String
    , capacity : OptionalArgument Int
    , maxSpecialPupils : OptionalArgument Int
    , dayIDs : OptionalArgument (List IdScalarCodecs.Id)
    }


type alias UpdateEventRequiredArguments =
    { id : IdScalarCodecs.Id }


updateEvent :
    (UpdateEventOptionalArguments -> UpdateEventOptionalArguments)
    -> UpdateEventRequiredArguments
    -> SelectionSet decodesTo Api.Object.Event
    -> SelectionSet decodesTo RootMutation
updateEvent fillInOptionals____ requiredArgs____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { title = Absent, capacity = Absent, maxSpecialPupils = Absent, dayIDs = Absent }

        optionalArgs____ =
            [ Argument.optional "title" filledInOptionals____.title Encode.string, Argument.optional "capacity" filledInOptionals____.capacity Encode.int, Argument.optional "maxSpecialPupils" filledInOptionals____.maxSpecialPupils Encode.int, Argument.optional "dayIDs" filledInOptionals____.dayIDs ((IdScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId) |> Encode.list) ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "updateEvent" (optionalArgs____ ++ [ Argument.required "id" requiredArgs____.id (IdScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId) ]) object____ Basics.identity


type alias DeleteEventRequiredArguments =
    { id : IdScalarCodecs.Id }


deleteEvent :
    DeleteEventRequiredArguments
    -> SelectionSet Bool RootMutation
deleteEvent requiredArgs____ =
    Object.selectionForField "Bool" "deleteEvent" [ Argument.required "id" requiredArgs____.id (IdScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId) ] Decode.bool


type alias AddPupilOptionalArguments =
    { special : OptionalArgument Bool }


type alias AddPupilRequiredArguments =
    { campaignID : IdScalarCodecs.Id
    , name : String
    , class : String
    }


addPupil :
    (AddPupilOptionalArguments -> AddPupilOptionalArguments)
    -> AddPupilRequiredArguments
    -> SelectionSet decodesTo Api.Object.Pupil
    -> SelectionSet decodesTo RootMutation
addPupil fillInOptionals____ requiredArgs____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { special = Absent }

        optionalArgs____ =
            [ Argument.optional "special" filledInOptionals____.special Encode.bool ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "addPupil" (optionalArgs____ ++ [ Argument.required "campaignID" requiredArgs____.campaignID (IdScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId), Argument.required "name" requiredArgs____.name Encode.string, Argument.required "class" requiredArgs____.class Encode.string ]) object____ Basics.identity


type alias UpdatePupilOptionalArguments =
    { name : OptionalArgument String
    , class : OptionalArgument String
    , special : OptionalArgument Bool
    }


type alias UpdatePupilRequiredArguments =
    { id : IdScalarCodecs.Id }


updatePupil :
    (UpdatePupilOptionalArguments -> UpdatePupilOptionalArguments)
    -> UpdatePupilRequiredArguments
    -> SelectionSet decodesTo Api.Object.Pupil
    -> SelectionSet decodesTo RootMutation
updatePupil fillInOptionals____ requiredArgs____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { name = Absent, class = Absent, special = Absent }

        optionalArgs____ =
            [ Argument.optional "name" filledInOptionals____.name Encode.string, Argument.optional "class" filledInOptionals____.class Encode.string, Argument.optional "special" filledInOptionals____.special Encode.bool ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "updatePupil" (optionalArgs____ ++ [ Argument.required "id" requiredArgs____.id (IdScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId) ]) object____ Basics.identity


type alias DeletePupilRequiredArguments =
    { id : IdScalarCodecs.Id }


deletePupil :
    DeletePupilRequiredArguments
    -> SelectionSet Bool RootMutation
deletePupil requiredArgs____ =
    Object.selectionForField "Bool" "deletePupil" [ Argument.required "id" requiredArgs____.id (IdScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId) ] Decode.bool


type alias AddPupilsOfClassRequiredArguments =
    { campaignID : IdScalarCodecs.Id
    , class : String
    , names : List String
    }


addPupilsOfClass :
    AddPupilsOfClassRequiredArguments
    -> SelectionSet decodesTo Api.Object.Pupil
    -> SelectionSet (List decodesTo) RootMutation
addPupilsOfClass requiredArgs____ object____ =
    Object.selectionForCompositeField "addPupilsOfClass" [ Argument.required "campaignID" requiredArgs____.campaignID (IdScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId), Argument.required "class" requiredArgs____.class Encode.string, Argument.required "names" requiredArgs____.names (Encode.string |> Encode.list) ] object____ (Basics.identity >> Decode.list)


type alias AssignPupilRequiredArguments =
    { pupilID : IdScalarCodecs.Id
    , eventID : IdScalarCodecs.Id
    , dayID : IdScalarCodecs.Id
    }


assignPupil :
    AssignPupilRequiredArguments
    -> SelectionSet decodesTo Api.Object.Day
    -> SelectionSet decodesTo RootMutation
assignPupil requiredArgs____ object____ =
    Object.selectionForCompositeField "assignPupil" [ Argument.required "pupilID" requiredArgs____.pupilID (IdScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId), Argument.required "eventID" requiredArgs____.eventID (IdScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId), Argument.required "dayID" requiredArgs____.dayID (IdScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId) ] object____ Basics.identity


type alias PupilChoiceRequiredArguments =
    { pupilID : IdScalarCodecs.Id
    , choices : List Api.InputObject.EventChoiceInput
    }


{-| assignAll(campaignID: ID!): Campaign!
-}
pupilChoice :
    PupilChoiceRequiredArguments
    -> SelectionSet Bool RootMutation
pupilChoice requiredArgs____ =
    Object.selectionForField "Bool" "pupilChoice" [ Argument.required "pupilID" requiredArgs____.pupilID (IdScalarCodecs.codecs |> Api.Scalar.unwrapEncoder .codecId), Argument.required "choices" requiredArgs____.choices (Api.InputObject.encodeEventChoiceInput |> Encode.list) ] Decode.bool
