-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (..)


type Campaign
    = Campaign


type Day
    = Day


type Event
    = Event


type EventChoice
    = EventChoice


type EventPupil
    = EventPupil


type Pupil
    = Pupil


type Service_
    = Service_
