-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Campaign exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Api.ScalarCodecs.Id Api.Object.Campaign
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


title : SelectionSet String Api.Object.Campaign
title =
    Object.selectionForField "String" "title" [] Decode.string


loginToken : SelectionSet String Api.Object.Campaign
loginToken =
    Object.selectionForField "String" "loginToken" [] Decode.string


days :
    SelectionSet decodesTo Api.Object.Day
    -> SelectionSet (List decodesTo) Api.Object.Campaign
days object____ =
    Object.selectionForCompositeField "days" [] object____ (Basics.identity >> Decode.list)


events :
    SelectionSet decodesTo Api.Object.Event
    -> SelectionSet (List decodesTo) Api.Object.Campaign
events object____ =
    Object.selectionForCompositeField "events" [] object____ (Basics.identity >> Decode.list)


pupils :
    SelectionSet decodesTo Api.Object.Pupil
    -> SelectionSet (List decodesTo) Api.Object.Campaign
pupils object____ =
    Object.selectionForCompositeField "pupils" [] object____ (Basics.identity >> Decode.list)
