-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Day exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Api.ScalarCodecs.Id Api.Object.Day
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


campaign :
    SelectionSet decodesTo Api.Object.Campaign
    -> SelectionSet decodesTo Api.Object.Day
campaign object____ =
    Object.selectionForCompositeField "campaign" [] object____ Basics.identity


title : SelectionSet String Api.Object.Day
title =
    Object.selectionForField "String" "title" [] Decode.string


events :
    SelectionSet decodesTo Api.Object.EventPupil
    -> SelectionSet (List decodesTo) Api.Object.Day
events object____ =
    Object.selectionForCompositeField "events" [] object____ (Basics.identity >> Decode.list)
