-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.EventPupil exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import CustomScalarCodecs
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


event :
    SelectionSet decodesTo Api.Object.Event
    -> SelectionSet decodesTo Api.Object.EventPupil
event object____ =
    Object.selectionForCompositeField "event" [] object____ Basics.identity


pupils :
    SelectionSet decodesTo Api.Object.Pupil
    -> SelectionSet (List decodesTo) Api.Object.EventPupil
pupils object____ =
    Object.selectionForCompositeField "pupils" [] object____ (Basics.identity >> Decode.list)
