-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Event exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import IdScalarCodecs
import Json.Decode as Decode


id : SelectionSet IdScalarCodecs.Id Api.Object.Event
id =
    Object.selectionForField "IdScalarCodecs.Id" "id" [] (IdScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


campaign :
    SelectionSet decodesTo Api.Object.Campaign
    -> SelectionSet decodesTo Api.Object.Event
campaign object____ =
    Object.selectionForCompositeField "campaign" [] object____ Basics.identity


title : SelectionSet String Api.Object.Event
title =
    Object.selectionForField "String" "title" [] Decode.string


capacity : SelectionSet Int Api.Object.Event
capacity =
    Object.selectionForField "Int" "capacity" [] Decode.int


maxSpecialPupils : SelectionSet Int Api.Object.Event
maxSpecialPupils =
    Object.selectionForField "Int" "maxSpecialPupils" [] Decode.int
