-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Pupil exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import CustomScalarCodecs
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet CustomScalarCodecs.Id Api.Object.Pupil
id =
    Object.selectionForField "CustomScalarCodecs.Id" "id" [] (CustomScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


campaign :
    SelectionSet decodesTo Api.Object.Campaign
    -> SelectionSet decodesTo Api.Object.Pupil
campaign object____ =
    Object.selectionForCompositeField "campaign" [] object____ Basics.identity


loginToken : SelectionSet String Api.Object.Pupil
loginToken =
    Object.selectionForField "String" "loginToken" [] Decode.string


name : SelectionSet String Api.Object.Pupil
name =
    Object.selectionForField "String" "name" [] Decode.string


class : SelectionSet String Api.Object.Pupil
class =
    Object.selectionForField "String" "class" [] Decode.string


isSpecial : SelectionSet Bool Api.Object.Pupil
isSpecial =
    Object.selectionForField "Bool" "isSpecial" [] Decode.bool


choices :
    SelectionSet decodesTo Api.Object.EventChoice
    -> SelectionSet (List decodesTo) Api.Object.Pupil
choices object____ =
    Object.selectionForCompositeField "choices" [] object____ (Basics.identity >> Decode.list)
