name: Build client and server and run all tests and checks

run-name : New push by ${{ github.actor }}

on:
  -push

jobs:
  run-default-task:
    steps:
      - uses: actions/checkout@v3
      - run: task
