name: Build client and server and run all tests and checks

on:
  - pull_request

jobs:
  client-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Taskfile (https://taskfile.dev)
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin

      - name: Install Elm (https://elm-lang.org/)
        uses: jorelali/setup-elm@v5
        with:
          elm-version: 0.19.1

      - name: Run build task as defined in Taskfile.yaml
        run: task client:build

  client-elm-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Taskfile (https://taskfile.dev)
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin

      - name: Install Elm (https://elm-lang.org/)
        uses: jorelali/setup-elm@v5
        with:
          elm-version: 0.19.1

      - name: Setup Node.js (https://nodejs.org)
        uses: actions/setup-node@v3
        with:
          node-version: '20.5.1'

      - name: Install elm-review
        run: npm install --global elm-review

      - name: Run client:review task
        run: task client:review


  server-test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Taskfile (https://taskfile.dev)
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin

      - name: Set up Go (https://go.dev)
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'

      - name: Install Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run build task as defined in Taskfile.yaml
        run: task server:build


