name: Build project and run all tests and checks

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install and set up Nix
        uses: cachix/install-nix-action@v25
        #with:
        #  nix_path: nixpkgs=channel:nixpkgs-unstable

      # https://nix.dev/tutorials/nixos/continuous-integration-github-actions

      # - name: Enable Magic Nix Cache
      #   uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Configure Nix to use the devenv cache provided by Cachix to speed up the installation
        uses: cachix/cachix-action@v14
        with:
          name: devenv

      - name: Install devenv.sh
        # run: nix profile install tarball+https://install.devenv.sh/latest
        run: nix-env -if https://install.devenv.sh/latest

      - name: Install roc
        run: devenv shell task get-roc

      - run: ldd roc_nightly-linux_x86_64-2024-03-20-ad78e04/roc

      - run: devenv shell ldd roc_nightly-linux_x86_64-2024-03-20-ad78e04/roc

      - name: Run tests
        shell: devenv shell bash -- -e {0}
        run: task test

      - name: Build project
        run: devenv shell task build

